version: '3'

services:
  protected-resource:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 5001:5001
    command: npm run map-debug
